name: 构建jdk11镜像
on:
  workflow_call:
    inputs:
      allowed-author:
        required: true
        type: string

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3.3.0
        with:
          repository: 'dooubb/action-test'
      - name: 测试
        run: |
            echo ${{ secrets.docker_user_name }}
            echo ${{ secrets.docker_password }}

      - name: 登录dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.docker_user_name }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.docker_password }}
      # - name: 给脚本添加执行权限
      #   if: ${{ success() }}
      #   run: |
      #     sudo chmod +x jdk11/build.sh
      - name: build镜像
        if: ${{ success() }}
        run: |
          bash -x ./jdk11/build.sh --build
      - name: 测试镜像
        if: ${{ success() }}
        run: |
          bash -x ./jdk11/build.sh --test
      - name: 推送镜像
        if: ${{ success() }}
        run: |
          bash -x ./jdk11/build.sh --push